@RequiredAndNullable_HostAddress = http://localhost:5176

POST {{RequiredAndNullable_HostAddress}}/sample/
Accept: application/json
Content-Type: application/json

{
  "optional": "optional",
  "required": "required"
}

###

POST {{RequiredAndNullable_HostAddress}}/sample/
Accept: application/json
Content-Type: application/json

{
  "required": "required"
}

###

POST {{RequiredAndNullable_HostAddress}}/sample/
Accept: application/json
Content-Type: application/json

{
}

###
